### ISSUE TITLE
check faker factory.

### ISSUE THREAD

**Issue by gokigoks** [yajra/laravel-datatables-demo#1]
I ran the seeder and I got a sqlstate[23000] integrity constraint violation for duplicate entry of a certain 'qmaggio@gmail.com' 

anyways, awesome demo and a more awesome package. thumbs up pare galing! :palm_tree:

**Comment by yajra** [comment]
Oh cool, someone already tried the demo. It's still work in progress but will take note of this! thanks for feedback! :beers:

**Comment by gokigoks** [comment]
Nice! and by the way, I've hit a dry wall trying all approaches to a responsive datatables and I'm betting my chips on this package. thanks for this! But if you could do more explanation/documentations on how this works, it would really help newbs like me who try your package :+1:
