### ISSUE TITLE
Json responce data key not showing data in key value pair

### ISSUE THREAD

**Issue by hassandad** [yajra/laravel-datatables-demo#10]
Hi Yajra,

I am having an issue while implementing data tables. I am running your demo app on my local machine and it works perfect. However i am implementing very simple server side example. But i am having issue when DATA key of json returned from server does not contain results in key value pair thats why i am unable to access colums using their index name rather than i am able to access them using index number like 0,1,2. I am doing this

$vessel = Vessel::select(['id','Name','RegistrationNo','created_at','updated_at']);
return Datatables::of($vessel)->make();

and here i copies piece of json result data index... 
"data":[[1,"Lorem ipsum","REG-1","2015-07-10 07:28:43"
,"2015-08-03 12:12:10"],[2,"Large Boat","REG-2","2015-07-10 07:28:43","2015-07-10 07:28:43"]

My JS Code:

$(function() {
        $('#vessel-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('vessel.data') !!}',
            columns: [
                {data: '0', name: 'id'},
                {data: '1', name: 'Name'},
                {data: '2', name: 'RegistrationNo'},
                {data: '3', name: 'created_at'},
                {data: '4', name: 'updated_at'},
            ]
        });
    });
</script>

You can see i am unable to access them using their key name becuase data is not comming in key value pair.  Json in your demo send key value pair data but why not in my case. may be its related to laravel  but i am not sure please help me..

**Comment by yajra** [comment]
@hassandad , since you're using `make(false)`. No need to set the columns attributes because the data will be automatically displayed according to how you selected your query.


```js
$(function() {
  $('#vessel-table').DataTable({
    processing: true,
    serverSide: true,
    ajax: '{!! route('vessel.data') !!}'
  });
});
```

**Comment by yajra** [comment]
And I think you use should integer and not string casted index.
```js
{data: '0', name: 'id'},
```
to
```js
{data: 0, name: 'id'},
```

**Comment by hassandad** [comment]
Thanks yajra for such fast responce. Actually i am not using make(false), i am using simple make as you can see in my question . But i want to access data using key value like this

columns: [
{data: 'id', name: 'id'},
{data: 'Name', name: 'Name'},
{data: 'RegistrationNo', name: 'RegistrationNo'},
{data: 'created_at', name: 'created_at'},
{data: 'updated_at', name: 'updated_at'},
]

but data in json responce is not coming in key value pair thats why i am forced to use integer indexes  which is not good as change in sql query will also force me change column indexes in html as well. Currently i am able to make it work but without index key string name. I want to access it with string index key name.

**Comment by yajra** [comment]
@hassandad , false is the default value when you did not submit a value on `make()` method. If you want key value pairs then you should use `make(true)` instead to return an object instead of array.

**Comment by hassandad** [comment]
@yajra Ok great. it worked. Thank you so very much for writing such a good library for laravel. You saved my time. Thanks again for such fast responce :)
