### ISSUE TITLE
Demo get ajax table error

### ISSUE THREAD

**Issue by ezekel** [yajra/laravel-datatables-demo#11]
Hi, can I ask, I set up your demo in my windows8.1 machine some demo examples have datatables ajax-error.

like this uri
http://localhost:7777/fluent/dt-row

I get error sometimes during page load, sometimes works fine, then when I tried to paginate I get also error..

Thank you in advance.

**Comment by yajra** [comment]
Sorry for late reply. Overlooked issues here. Are you using `artisan serve`? There were several issues that are raised when using artisan serve so I suggest you use a LAMPP/WAMP stack or better use Homestead if possible. Thanks!

**Comment by yajra** [comment]
This issue was already confirmed that was caused by `artisan serve`. Thanks!
