### ISSUE TITLE
Send ajax request with different column names and different ajax url every time

### ISSUE THREAD

**Issue by hassandad** [yajra/laravel-datatables-demo#12]
Hi,

I am implementing datatables using ajax using your datables library. I have a scenerio where i send ajax request on different url based on selectbox change event. And every url get data from a different table. So i need to change column information everytime with new request. However i am unable to do it. I can change ajax url on change of select box like this 

table.ajax.url('{!! url("recyclebin/portclearance") !!}').load();  

But i am unable to find way to change column information. Is it something you can help me with??. I would be gratefull to you.

**Comment by yajra** [comment]
Changing columns dynamically would require a lot of js. See this API link to get you started. https://datatables.net/reference/option/columns. Basically, you have to define each column on your js with the `title` attribute. Afterwards, you have to manipulate the columns to be displayed based on your requirements. And I guess asking on datatables.net forum would give you more possible answers. For the url, I suggest you just send to one url and just add additional parameter like `task=table1` then reroute it accordingly.

I think I made something like this before and what I did was I created multiple tables and just display the appropriate one upon request. A bit hacky but it works. ^_^
