### ISSUE TITLE
Feature Request: Generating a checkboxes column, and submitting the checked rows

### ISSUE THREAD

**Issue by MeiRct** [yajra/laravel-datatables-demo#14]
@yajra 
Hi Arjay,

Any chance you have time to implement a generating of a checkboxes column (a checkbox for each row), and then an ability to check several rows, and submit the ids (as an array, I guess) through a controller function in Laravel to a separate view?
It can be useful in some situations.

Thanks in advance :)

**Comment by yajra** [comment]
hi @MeiRct,

Yeah, I agree that having a checkbox is useful. However, have you tried select plugin of dataTables? It's quite easy to implement so I suggest you give it a try. See this link for ref: https://datatables.net/extensions/select/

Will try to add more advance demo if I had the chance.

Regards,

**Comment by yajra** [comment]
@MeiRct, sorry for overlooking this issue. I am already using checkbox via `select` extension of datatables and it works great out of the box. Better check it out. Thanks!

**Comment by MeiRct** [comment]
@yajra, is there any chance that you can please combine an example of the `select` extenstion usage in the demo project?
I'm curious to see how you're passing the IDs in Laravel's way, especially to Eloquent.

**Comment by yajra** [comment]
@MeiRct, will try to add a demo for this. For a quick note, this is how I passed the id in Laravel.

```js
// on button click event.
var rows = table.rows({selected: true}).data().pluck('id');
var selected = [];
for (var i = 0; i < table.rows({selected: true}).count(); i++) {
  selected.push(rows[i]);
}

// post via ajax
$.post(url, {id: selected}, function (json) {
    table.ajax.reload();
    // process response
});
```

**Comment by tpfuhl** [comment]
@yajra, I cannot figure out where to put the ```select: true``` option in my Laravel5.1 project. I access Datatables as  the return value from a Controller, like this:  ```return Datatables::of($items)->...->make()```. Any hint is welcome !
