### ISSUE TITLE
Choose columns for export using Datatables as Service

### ISSUE THREAD

**Issue by Skintillion** [yajra/laravel-datatables-demo#15]
Is there a way to choose the columns present in the Excel, CSV, and PDF options?

I found 

```protected $exportColumns = '*';```

but I am not sure where to modify this properly.

**Comment by yajra** [comment]
Yes, you can use the `exportColumns` and set an array of fields to export. Still on development but it should work. Just please report if you found any bugs. Thanks!

**Comment by Skintillion** [comment]
Got it to work thanks. 

'''
public function ajax()
    {
        //----Columns for Excel and CSV export (used to avoid html code in export)----//
        $this->exportColumns = array(
            'id',
            'status',
            'typetext',
            'tagname',
            'company'
            );

        return $this->datatables
            ->of($this->query())
            ->editColumn('value', '<i class="fa fa-dollar"></i>{!! number_format($value, 2, ".",",") !!}')

            

            ->make(true);
    }
'''

**Comment by minedun6** [comment]
i got it with somethings else that is actually quite easier,

   `protected function getColumns()
    {
        return [
            'code' => ['name' => 'code', 'data' => 'code', 'title' => 'Code'],
            'name' => ['name' => 'name', 'data' => 'name', 'title' => 'Name'],
            'bought_at' => ['name' => 'bought_at', 'data' => 'bought_at', 'title' => 'Bought At'],
            'duration' => ['name' => 'duration', 'data' => 'duration', 'title' => 'Duration'],
            'created_at',
            'updated_at',
            'actions' => ['searchable' => false, 'exportable' => 'false', 'printable' => false]
        ];
    }`
