### ISSUE TITLE
Error search mb_strtolower()

### ISSUE THREAD

**Issue by wiyfn** [yajra/laravel-datatables-demo#19]
ErrorException in Str.php line 169: mb_strtolower() expects parameter 1 to be string, array given.

` $data = $database->with('busines')->where('show', '=', 1)->get();
  return Datatables::of($data)->make(true)`

```
var table = $('#database-table').DataTable({
					"processing": true,
					"serverSide": true,
                    "ajax": 'db/details',
                    "columns": [
                        {
                            "className":      'details-control',
                            "orderable":      false,
                            "data":           null,
                            "defaultContent": '',
                            "width": "25px",
                        },
                        {"data": 'title', name: 'title', "width": "100px"},
                        {"data": 'busines[].name', "orderable": false, "searchable":true, name: 'busines', "width": "250px"},
                        {"data": 'location', name: 'location', "width": "150px"},
                        {"data": 'legal_address', name: 'legal_address', "width": "150px"},
                        {"data": 'contact_person', name: 'contact_person', "width": "100px"},
                        {"data": 'phone', name: 'phone', "width": "150px"},
                        {"data": 'count', name: 'count', "width": "40px"}

                    ],


                });

                $('select#busines').on('change', function() {
                    var val = $.fn.dataTable.util.escapeRegex($(this).val());
                    table.columns(2).search(val).draw();
                } );`
```

Search column busines[].name

**Comment by yajra** [comment]
Does the table name is really `busines[]`? I think you need to remove `[]` as it seems to being treated as an array? Also see this [eager loading demo](http://datatables.yajrabox.com/eloquent/relationships) for ref. BTW, if ever, please post new issue on main package repo. I mostly overlooked all the issues here. Thanks!

**Comment by njwangchuan** [comment]
@yajra ,hi , i just face the same question and find the key point.

The search fillter can not run on "->get()" function.

> $data = $database->with('busines')->where('show', '=', 1)->**get()**;

when i change to "select()", every thing is ok.

> $data = $database->with('busines')->select(array('column1','coulum2');

**Comment by C4rr13rX** [comment]
For others that run into this issue, if you have custom data in a column, set the searchable property to false: columns: [
			{data: null,
			defaultContent: '<input type="checkbox" class="styled">',
			searchable: false}
