### ISSUE TITLE
ajax responds with an error 404 on add/edit/remove page

### ISSUE THREAD

**Issue by gokigoks** [yajra/laravel-datatables-demo#3]
The problem is it wont load the add/edit/remove page and localhost:8000 throws an alert saying 
 "DataTables warning: table id=users-table - Ajax error"

This problem also happens with DT row option page. but oddly enough, sometimes it loads.

And when i view the content of the link through the chrome console, a notFoundHttpException was thrown by laravel. I will look into this but I doubt ill find it.

**Comment by yajra** [comment]
Thank you for testing. The demo is not yet fully tested and some example are not yet done. Will look at this later on my free time. Thanks!

**Comment by yajra** [comment]
just checked this one and can't reproduce the error. it's working well on my side.
