### ISSUE TITLE
Post column global search - wrong variable passed

### ISSUE THREAD

**Issue by sameerpanjwani** [yajra/laravel-datatables-demo#4]
Refer [code here](https://github.com/yajra/laravel-datatables-demo/blob/99331189fb6db714181ba1605abb9f8eb81cb2fb/app/Http/Controllers/EloquentController.php#L305-307)

should be ["%{$keyword}%"] instead of  ["%{$column['search']['value']

**Comment by yajra** [comment]
Yes, good catch! Fixed and Thanks!
