### ISSUE TITLE
Example with Row details and Join Queries

### ISSUE THREAD

**Issue by lmatab** [yajra/laravel-datatables-demo#5]
Hello Yaijra,

I am getting to  know a little  bit more your package and it is very cool.

 I am trying to make a  table with the characteristics of the row details  example mixed with the Join Queries one, so  when  the user  click on the plus button I can  show data from  the  second table that is related to the  first  one.

For  instance in the  post and  user tables we  can show the post details  of that user when clicked on the plus button.

Can I just  request  the  data like in the join queries example and set the additional fields to hidden  or  something and later   request them  to be   shown in the details  just  like  you  did  with the {{name}} and {{email}} fields?

Do you  have an example with this  behaviour?

Thanks

**Comment by yajra** [comment]
@lmatab , you can create an Eloquent with join queries or just use the eager loading methods. On your js, you can just manipulate all the object data returned in the output. On row details example, all row data is passed on the template engine. This means that you can access eager loaded data like `{{user.email}}`. I suggest inspecting the ajax output via firebug/dev tools and verify the `data` on json response. Also, you don't need to hide the column, the data is available on the api but only displays value depending on you `columns` definition.

Note: data added via eager loading is not searchable/orderable. If you need these functionalities then you should use join queries.

**Comment by yajra** [comment]
Btw, I don't have examples of this behavior but will try to it on my free time. Thanks!

**Comment by lmatab** [comment]
Hello, Thanks for such a fas reply. I will try it and let you know.

**Comment by yajra** [comment]
We already this on demo page now. Thanks!
