### ISSUE TITLE
Textbox  width in column search example

### ISSUE THREAD

**Issue by lmatab** [yajra/laravel-datatables-demo#6]
Hello.

The column example works  just great, but  when  adding the search  textbox only to few fields the  table does not  show  the  results  with the appropiated  width.

I tried to add the class="col-md-1  but  it is not responding, so for example  the id  is  column is larger than it  shoulded.

I would like that this keep  the  same width that the  table has :

                    <table id="users-table" class="table table-hover">
                        <thead>
                        <tr>
                            <th class="col-md-1">Id</th>
                            <th class="col-md-1" >Order Number</th>

</tr>
                     
   </thead>

  </tr>
  
                        <tfoot>
                        <tr>
                            <th class="col-md-1" >Id</th>
                            <th class="col-md-1">Order Number</th>
                        </tr>
                        </tfoot>--}}

                    </table>

Any suggestions?

**Comment by yajra** [comment]
@lmatab, Sorry, overlooked the issues here on demo repo. Please post on the main package repo in case you have issues. Thanks!
