### ISSUE TITLE
Column Searching

### ISSUE THREAD

**Issue by xLink** [yajra/laravel-datatables-demo#7]
The Datatable setup you have here - http://datatables.yajrabox.com/collection/multi-filter-select uses escapeRegex() on the value before throwing it at PHP, cause of this some characters get escaped, which means they need to be unescaped to be used as was intended in the search results.

**Comment by yajra** [comment]
@xLink , sorry overlooked issues here. Yes, the regex escapes some character. I have updated some time ago and removed the regex thing. Thanks!
