### ISSUE TITLE
How to use blade templates into datatables?

### ISSUE THREAD

**Issue by tarunhere** [yajra/laravel-datatables-demo#8]
Hi,
I have used datatables and I am adding a column to add actions column. In which user have different permissions like edit, update or delete.

I have create a blade template as admin/action.blade.php, which checks for canUser("edit_admin") with admin->id and displays the edit button in table.

how can I use same template in 
```
->addColumn('actions', view(admin.action));
```
How can we use template here.

**Comment by yajra** [comment]
use the closure and return the rendered view. I think it's something like this.

```php
->addColumn('actions', function($model) {
   return view('admin.actions', compact('model')->render();
})
```

**Comment by tarunhere** [comment]
I was missing `->render()`
Thanks yajra for quick response and a wonderful library :)
