### ISSUE TITLE
How do you launch the demo ?

### ISSUE THREAD

**Issue by ssnukala** [yajra/laravel-datatables-demo#9]
I am new to laravel, so installed your package. 
Know enough to setup and run the demo, I even reset one of the user passwords to be able to login.
Once logged what page do I go to to see the Posts and Users
/datatables/users /datatables/posts do not work.
In your routes you just have 

Route::get('{view}', function($view) {
	if (view()->exists($view)) {
		return view($view);
	}

So not sure how or what page to go to to see the data tables in action. 

Please help or just include the instruction for the pages to see users and posts in the demo readme.

**Comment by yajra** [comment]
@ssnukala, I suggest you follow this quick tutorial http://datatables.yajrabox.com/starter. This route is a catch all route trick of Laravel.

```php
Route::get('{view}', function($view) {
if (view()->exists($view)) {
return view($view);
}
```
